In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Insert warehouse name here
warehouse_name = "OE"
work_code = "30"
base = "~/Lucas_Systems_Capstone_Project"

# Load your processed data (with assignment opens)
df = pd.read_parquet(f"{base}/data/processed/{warehouse_name}_detailed_withAO.parquet")

# Filter for specific Work Code
# df = df[df["WorkCode"] == work_code]

# Drop missing rows for important variables
# df = df.dropna(subset=['Weight', 'Cube', 'Level', 'Time_Delta_sec', 'Travel_Distance'])

In [11]:
df.columns

Index(['ActivityCode', 'UserID', 'WorkCode', 'AssignmentID', 'ProductID',
       'Quantity', 'Timestamp', 'LocationID', 'Prev_Timestamp',
       'Prev_LocationID', 'Time_Delta_sec', 'ProductCode', 'UnitOfMeasure',
       'Weight', 'Cube', 'Aisle', 'Bay', 'Level', 'Slot', 'Prev_Aisle',
       'Prev_Bay', 'Prev_Level', 'Prev_Slot', 'Aisle2', 'Bay2', 'Prev_Aisle2',
       'Prev_Bay2', 'LocKey', 'PrevLocKey', 'Travel_Distance'],
      dtype='object')

In [12]:
df["Date"] = df["Timestamp"].dt.date

In [13]:
df["Date"].unique()

array([datetime.date(2025, 9, 8), datetime.date(2025, 9, 9),
       datetime.date(2025, 11, 10), datetime.date(2025, 11, 11),
       datetime.date(2025, 11, 12), datetime.date(2025, 11, 13),
       datetime.date(2025, 12, 1), datetime.date(2025, 12, 2)],
      dtype=object)

In [19]:
df[df["ActivityCode"] == "AssignmentOpen"].head(5)

,ActivityCode,UserID,WorkCode,AssignmentID,ProductID,Quantity,Timestamp,LocationID,Prev_Timestamp,Prev_LocationID,...,Prev_Level,Prev_Slot,Aisle2,Bay2,Prev_Aisle2,Prev_Bay2,LocKey,PrevLocKey,Travel_Distance,Date
4279,AssignmentOpen,217,10,7717786,<NA>,<NA>,2025-09-08 13:40:23.160,<NA>,2025-09-08 13:33:53.247,5533326,...,1,1,<NA>,<NA>,24,41,<NA>|<NA>|||,24|41|||,NaN,2025-09-08
4282,AssignmentOpen,217,10,7717787,<NA>,<NA>,2025-09-08 13:50:38.933,<NA>,2025-09-08 13:50:36.450,698485,...,4,1,<NA>,<NA>,33,32,<NA>|<NA>|||,33|32|||,NaN,2025-09-08
4285,AssignmentOpen,217,10,7717788,<NA>,<NA>,2025-09-08 14:09:27.340,<NA>,2025-09-08 14:09:24.520,17501,...,5,2,<NA>,<NA>,35,35,<NA>|<NA>|||,35|35|||,NaN,2025-09-08
4289,AssignmentOpen,217,10,7717789,<NA>,<NA>,2025-09-08 14:21:58.973,<NA>,2025-09-08 14:21:56.607,2318,...,5,4,<NA>,<NA>,36,21,<NA>|<NA>|||,36|21|||,NaN,2025-09-08
4292,AssignmentOpen,217,10,7717790,<NA>,<NA>,2025-09-08 14:33:11.197,<NA>,2025-09-08 14:33:08.260,4779329,...,4,5,<NA>,<NA>,84,04,<NA>|<NA>|||,84|04|||,NaN,2025-09-08

In [20]:
df.columns

Index(['ActivityCode', 'UserID', 'WorkCode', 'AssignmentID', 'ProductID',
       'Quantity', 'Timestamp', 'LocationID', 'Prev_Timestamp',
       'Prev_LocationID', 'Time_Delta_sec', 'ProductCode', 'UnitOfMeasure',
       'Weight', 'Cube', 'Aisle', 'Bay', 'Level', 'Slot', 'Prev_Aisle',
       'Prev_Bay', 'Prev_Level', 'Prev_Slot', 'Aisle2', 'Bay2', 'Prev_Aisle2',
       'Prev_Bay2', 'LocKey', 'PrevLocKey', 'Travel_Distance', 'Date'],
      dtype='object')

In [ ]:
# pd.set_option("display.max_rows", None)

In [21]:
dfsmall = df[["ActivityCode", "UserID", "WorkCode", "AssignmentID", "Timestamp", "Date", "Time_Delta_sec", "Weight", "Cube", "Travel_Distance"]]

In [22]:
dfsmall.head(5)

,ActivityCode,UserID,WorkCode,AssignmentID,Timestamp,Date,Time_Delta_sec,Weight,Cube,Travel_Distance
0,PickPut,143,30,7717848,2025-09-08 12:11:50.830,2025-09-08,NaN,0.0113,0.005,NaN
1,PickPut,143,30,7717860,2025-09-08 12:12:18.127,2025-09-08,27.297,0.0300,0.016,21.0
2,PickPut,143,30,7717908,2025-09-08 12:15:46.650,2025-09-08,208.523,0.0300,0.016,0.0
3,PickPut,143,30,7717921,2025-09-08 12:16:30.470,2025-09-08,43.820,0.5000,0.139,0.0
4,PickPut,143,30,7717920,2025-09-08 12:18:00.970,2025-09-08,90.500,0.5000,0.139,0.0

In [25]:
dfsmall["UserID"].unique()

array(['143', '217', '221', '262', '322', '323', '348', '390', '412',
       '414', '419', '434', '435', '439', '440', '444', '458', '460',
       '461', '467', '471', '473', '475', '476', '479', '480', '484',
       '488', '494', '496', '497', '498', '499', '501', '502', '503',
       '504', '64', '67', '90'], dtype=object)

In [37]:
rows = []

for id in dfsmall["UserID"].unique():
    for date in dfsmall["Date"].unique():
        row_data = {"UserID": id, 
                    "Date": date, 
                    "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
                    "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
                    "Number of AssignmentID": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date]["AssignmentID"]).nunique()}

        rows.append(row_data)

ao_rows = pd.DataFrame(rows)

/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentID": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date]["AssignmentID"]).nunique()}
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentID": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date]["AssignmentID"]).nunique()}
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentID": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date]["AssignmentID"]).nunique()}
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentID": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date]["AssignmentID"]).nunique()}
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentID": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date]["AssignmentID"]).nunique()}
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentID": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date]["AssignmentID"]).nunique()}
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentID": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date]["AssignmentID"]).nunique()}
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentID": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date]["AssignmentID"]).nunique()}
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentID": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date]["AssignmentID"]).nunique()}
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentID": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date]["AssignmentID"]).nunique()}
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentID": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date]["AssignmentID"]).nunique()}
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentID": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date]["AssignmentID"]).nunique()}
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentID": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date]["AssignmentID"]).nunique()}
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of AssignmentOpen": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "AssignmentOpen"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "Number of PickPut": (dfsmall[dfsmall['UserID'] == id][dfsmall["Date"] == date][dfsmall["ActivityCode"] == "PickPut"]).shape[0],
/var/folders/r9/zx84vhy57q9_n8tk5dnw8g980000gn/T/ipykernel_36489/1548042026.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

In [38]:
ao_rows

,UserID,Date,Number of AssignmentOpen,Number of PickPut,Number of AssignmentID
0,143,2025-09-08,0,622,413
1,143,2025-09-09,0,419,295
2,143,2025-11-10,0,683,432
3,143,2025-11-11,0,401,249
4,143,2025-11-12,0,488,304
5,143,2025-11-13,0,626,380
6,143,2025-12-01,0,871,520
7,143,2025-12-02,0,26,14
8,217,2025-09-08,102,299,231
9,217,2025-09-09,60,224,164
10,217,2025-11-10,0,229,226
11,217,2025-11-11,17,217,67
12,217,2025-11-12,0,254,254
13,217,2025-11-13,0,146,139
14,217,2025-12-01,0,257,204
15,217,2025-12-02,12,292,204
16,221,2025-09-08,0,529,337
17,221,2025-09-09,0,301,199
18,221,2025-11-10,0,525,302
19,221,2025-11-11,0,388,241
20,221,2025-11-12,0,375,223
21,221,2025-11-13,0,561,304
22,221,2025-12-01,0,0,0
23,221,2025-12-02,0,569,330
24,262,2025-09-08,0,768,494
25,262,2025-09-09,0,303,218
26,262,2025-11-10,0,676,402
27,262,2025-11-11,0,452,276
28,262,2025-11-12,0,509,334
29,262,2025-11-13,0,596,373
30,262,2025-12-01,0,822,521
31,262,2025-12-02,0,493,291
32,322,2025-09-08,0,225,225
33,322,2025-09-09,0,132,132
34,322,2025-11-10,0,0,0
35,322,2025-11-11,0,185,182
36,322,2025-11-12,0,170,170
37,322,2025-11-13,0,189,189
38,322,2025-12-01,0,291,291
39,322,2025-12-02,0,194,194
40,323,2025-09-08,0,0,0
41,323,2025-09-09,13,159,8
42,323,2025-11-10,17,118,18
43,323,2025-11-11,3,97,59
44,323,2025-11-12,11,134,9
45,323,2025-11-13,9,128,17
46,323,2025-12-01,0,0,0
47,323,2025-12-02,11,140,8
48,348,2025-09-08,0,374,374
49,348,2025-09-09,0,0,0
50,348,2025-11-10,0,0,0
51,348,2025-11-11,0,0,0
52,348,2025-11-12,0,0,0
53,348,2025-11-13,0,159,149
54,348,2025-12-01,0,0,0
55,348,2025-12-02,0,0,0
56,390,2025-09-08,6,222,200
57,390,2025-09-09,4,158,147
58,390,2025-11-10,8,150,93
59,390,2025-11-11,8,227,192
60,390,2025-11-12,4,175,138
61,390,2025-11-13,9,100,34
62,390,2025-12-01,4,388,373
63,390,2025-12-02,4,197,177
64,412,2025-09-08,0,113,63
65,412,2025-09-09,0,0,0
66,412,2025-11-10,0,0,0
67,412,2025-11-11,0,0,0
68,412,2025-11-12,0,0,0
69,412,2025-11-13,0,0,0
70,412,2025-12-01,0,158,102
71,412,2025-12-02,0,48,32
72,414,2025-09-08,0,807,527
73,414,2025-09-09,0,485,341
74,414,2025-11-10,0,705,450
75,414,2025-11-11,0,485,328
76,414,2025-11-12,0,543,367
77,414,2025-11-13,0,0,0
78,414,2025-12-01,0,932,617
79,414,2025-12-02,0,33,15
80,419,2025-09-08,24,296,158
81,419,2025-09-09,21,270,188
82,419,2025-11-10,12,537,472
83,419,2025-11-11,5,234,220
84,419,2025-11-12,0,0,0
85,419,2025-11-13,0,0,0
86,419,2025-12-01,0,0,0
87,419,2025-12-02,0,0,0
88,434,2025-09-08,0,0,0
89,434,2025-09-09,0,369,272
90,434,2025-11-10,0,286,245
91,434,2025-11-11,0,370,250
92,434,2025-11-12,0,250,207
93,434,2025-11-13,0,360,318
94,434,2025-12-01,0,818,547
95,434,2025-12-02,0,384,301
96,435,2025-09-08,0,290,260
97,435,2025-09-09,3,206,186
98,435,2025-11-10,0,621,615
99,435,2025-11-11,8,332,302
100,435,2025-11-12,8,369,306
101,435,2025-11-13,0,248,225
102,435,2025-12-01,4,430,408
103,435,2025-12-02,3,526,515
104,439,2025-09-08,0,388,238
105,439,2025-09-09,0,174,105
106,439,2025-11-10,0,321,181
107,439,2025-11-11,0,71,44
108,439,2025-11-12,0,260,169
109,439,2025-11-13,0,431,292
110,439,2025-12-01,0,506,245
111,439,2025-12-02,0,21,11
112,440,2025-09-08,20,494,250
113,440,2025-09-09,5,419,390
114,440,2025-11-10,0,0,0
115,440,2025-11-11,0,0,0
116,440,2025-11-12,0,0,0
117,440,2025-11-13,0,0,0
118,440,2025-12-01,0,0,0
119,440,2025-12-02,0,0,0
120,444,2025-09-08,0,0,0
121,444,2025-09-09,7,225,59
122,444,2025-11-10,4,316,193
123,444,2025-11-11,17,194,34
124,444,2025-11-12,13,251,106
125,444,2025-11-13,12,257,101
126,444,2025-12-01,12,293,130
127,444,2025-12-02,13,295,134
128,458,2025-09-08,0,0,0
129,458,2025-09-09,0,0,0
130,458,2025-11-10,0,0,0
131,458,2025-11-11,0,0,0
132,458,2025-11-12,0,0,0
133,458,2025-11-13,0,0,0
134,458,2025-12-01,0,91,28
135,458,2025-12-02,0,0,0
136,460,2025-09-08,0,764,516
137,460,2025-09-09,0,358,248
138,460,2025-11-10,0,692,441
139,460,2025-11-11,0,386,262
140,460,2025-11-12,0,405,280
141,460,2025-11-13,0,520,356
142,460,2025-12-01,0,864,520
143,460,2025-12-02,0,602,366
144,461,2025-09-08,0,0,0
145,461,2025-09-09,2,166,92
146,461,2025-11-10,0,240,160
147,461,2025-11-11,0,175,121
148,461,2025-11-12,2,252,160
149,461,2025-11-13,0,203,142
150,461,2025-12-01,5,226,149
151,461,2025-12-02,5,246,151
152,467,2025-09-08,0,708,496
153,467,2025-09-09,0,356,277
154,467,2025-11-10,0,618,407
155,467,2025-11-11,0,431,303
156,467,2025-11-12,0,413,283
157,467,2025-11-13,0,576,395
158,467,2025-12-01,0,654,418
159,467,2025-12-02,0,552,371
160,471,2025-09-08,0,730,522
161,471,2025-09-09,0,317,235
162,471,2025-11-10,0,722,450
163,471,2025-11-11,0,417,295
164,471,2025-11-12,0,486,318
165,471,2025-11-13,0,661,416
166,471,2025-12-01,0,0,0
167,471,2025-12-02,0,538,356
168,473,2025-09-08,0,0,0
169,473,2025-09-09,0,391,280
170,473,2025-11-10,0,717,427
171,473,2025-11-11,0,378,242
172,473,2025-11-12,0,477,301
173,473,2025-11-13,0,649,436
174,473,2025-12-01,0,593,375
175,473,2025-12-02,0,510,315
176,475,2025-09-08,23,335,198
177,475,2025-09-09,15,215,135
178,475,2025-11-10,10,400,362
179,475,2025-11-11,2,413,403
180,475,2025-11-12,0,443,443
181,475,2025-11-13,8,323,309
182,475,2025-12-01,14,493,320
183,475,2025-12-02,0,90,90
184,476,2025-09-08,0,324,256
185,476,2025-09-09,1,295,259
186,476,2025-11-10,0,261,179
187,476,2025-11-11,3,235,207
188,476,2025-11-12,8,251,171
189,476,2025-11-13,0,0,0
190,476,2025-12-01,11,256,114
191,476,2025-12-02,12,265,185
192,479,2025-09-08,0,558,408
193,479,2025-09-09,0,316,229
194,479,2025-11-10,0,476,333
195,479,2025-11-11,0,437,276
196,479,2025-11-12,0,401,253
197,479,2025-11-13,0,603,351
198,479,2025-12-01,0,525,333
199,479,2025-12-02,0,0,0
200,480,2025-09-08,0,726,496
201,480,2025-09-09,0,441,323
202,480,2025-11-10,0,747,474
203,480,2025-11-11,0,430,283
204,480,2025-11-12,0,561,350
205,480,2025-11-13,0,0,0
206,480,2025-12-01,0,709,477
207,480,2025-12-02,0,618,416
208,484,2025-09-08,0,653,327
209,484,2025-09-09,0,316,168
210,484,2025-11-10,0,530,260
211,484,2025-11-11,0,358,155
212,484,2025-11-12,0,305,169
213,484,2025-11-13,0,463,206
214,484,2025-12-01,0,89,46
215,484,2025-12-02,0,112,54
216,488,2025-09-08,0,602,322
217,488,2025-09-09,0,361,197
218,488,2025-11-10,0,576,245
219,488,2025-11-11,0,331,183
220,488,2025-11-12,0,470,264
221,488,2025-11-13,0,569,265
222,488,2025-12-01,0,725,349
223,488,2025-12-02,0,635,315
224,494,2025-09-08,0,748,473
225,494,2025-09-09,0,402,281
226,494,2025-11-10,0,668,376
227,494,2025-11-11,0,405,265
228,494,2025-11-12,0,450,267
229,494,2025-11-13,0,644,374
230,494,2025-12-01,0,873,502
231,494,2025-12-02,0,585,391
232,496,2025-09-08,0,110,66
233,496,2025-09-09,0,16,9
234,496,2025-11-10,0,0,0
235,496,2025-11-11,0,0,0
236,496,2025-11-12,0,0,0
237,496,2025-11-13,0,0,0
238,496,2025-12-01,0,0,0
239,496,2025-12-02,0,0,0
240,497,2025-09-08,0,286,198
241,497,2025-09-09,4,214,159
242,497,2025-11-10,0,525,507
243,497,2025-11-11,1,367,321
244,497,2025-11-12,2,568,549
245,497,2025-11-13,0,399,398
246,497,2025-12-01,0,477,431
247,497,2025-12-02,5,519,478
248,498,2025-09-08,0,0,0
249,498,2025-09-09,3,419,354
250,498,2025-11-10,0,355,323
251,498,2025-11-11,3,330,284
252,498,2025-11-12,0,0,0
253,498,2025-11-13,0,718,717
254,498,2025-12-01,0,0,0
255,498,2025-12-02,0,693,679
256,499,2025-09-08,0,204,147
257,499,2025-09-09,3,166,100
258,499,2025-11-10,0,320,184
259,499,2025-11-11,2,211,138
260,499,2025-11-12,0,318,193
261,499,2025-11-13,0,277,181
262,499,2025-12-01,0,298,160
263,499,2025-12-02,2,302,194
264,501,2025-09-08,2,1017,1000
265,501,2025-09-09,4,328,262
266,501,2025-11-10,0,755,741
267,501,2025-11-11,3,318,208
268,501,2025-11-12,2,402,360
269,501,2025-11-13,0,242,169
270,501,2025-12-01,0,549,493
271,501,2025-12-02,2,522,484
272,502,2025-09-08,0,0,0
273,502,2025-09-09,0,0,0
274,502,2025-11-10,0,0,0
275,502,2025-11-11,0,0,0
276,502,2025-11-12,0,0,0
277,502,2025-11-13,5,182,147
278,502,2025-12-01,0,368,327
279,502,2025-12-02,0,279,166
280,503,2025-09-08,0,0,0
281,503,2025-09-09,0,0,0
282,503,2025-11-10,0,0,0
283,503,2025-11-11,0,0,0
284,503,2025-11-12,0,0,0
285,503,2025-11-13,0,45,45
286,503,2025-12-01,0,0,0
287,503,2025-12-02,0,0,0
288,504,2025-09-08,0,0,0
289,504,2025-09-09,0,0,0
290,504,2025-11-10,0,0,0
291,504,2025-11-11,0,0,0
292,504,2025-11-12,0,0,0
293,504,2025-11-13,0,0,0
294,504,2025-12-01,0,446,394
295,504,2025-12-02,0,37,21
296,64,2025-09-08,0,0,0
297,64,2025-09-09,0,0,0
298,64,2025-11-10,31,147,50
299,64,2025-11-11,54,145,39
300,64,2025-11-12,56,159,46
301,64,2025-11-13,27,157,48
302,64,2025-12-01,46,151,86
303,64,2025-12-02,0,55,55
304,67,2025-09-08,0,627,591
305,67,2025-09-09,0,256,172
306,67,2025-11-10,0,477,310
307,67,2025-11-11,0,404,213
308,67,2025-11-12,0,298,200
309,67,2025-11-13,0,586,338
310,67,2025-12-01,0,640,383
311,67,2025-12-02,0,463,319
312,90,2025-09-08,0,47,47
313,90,2025-09-09,2,34,26
314,90,2025-11-10,0,58,49
315,90,2025-11-11,0,38,28
316,90,2025-11-12,0,26,23
317,90,2025-11-13,0,0,0
318,90,2025-12-01,0,78,65
319,90,2025-12-02,21,55,35

In [51]:
user323 = dfsmall[(dfsmall["UserID"] == "323") & (dfsmall["Date"].astype(str) == "2025-12-02")]

In [65]:
user323[user323["AssignmentID"] == "8039503"].shape[0]

16

In [67]:
user323[user323["AssignmentID"] == "8039503"]

,ActivityCode,UserID,WorkCode,AssignmentID,Timestamp,Date,Time_Delta_sec,Weight,Cube,Travel_Distance
16205,AssignmentOpen,323,10,8039503,2025-12-02 14:04:13.263,2025-12-02,402.916,NaN,NaN,NaN
16206,PickPut,323,10,8039503,2025-12-02 14:11:30.870,2025-12-02,437.607,6.40,0.234,NaN
16207,PickPut,323,10,8039503,2025-12-02 14:12:35.107,2025-12-02,64.237,6.40,0.234,0.0
16208,PickPut,323,10,8039503,2025-12-02 14:14:28.983,2025-12-02,113.876,4.55,0.251,0.0
16209,PickPut,323,10,8039503,2025-12-02 14:16:55.893,2025-12-02,146.910,3.45,0.558,379.0
16210,PickPut,323,10,8039503,2025-12-02 14:21:30.577,2025-12-02,274.684,25.15,1.472,562.0
16211,PickPut,323,10,8039503,2025-12-02 14:21:48.630,2025-12-02,18.053,0.00,0.000,0.0
16212,PickPut,323,10,8039503,2025-12-02 14:25:02.000,2025-12-02,193.370,7.38,2.836,240.0
16213,PickPut,323,10,8039503,2025-12-02 14:28:23.720,2025-12-02,201.720,9.40,1.289,416.0
16214,PickPut,323,10,8039503,2025-12-02 14:29:36.950,2025-12-02,73.230,3.60,0.563,509.0
16215,PickPut,323,10,8039503,2025-12-02 14:31:14.150,2025-12-02,97.200,9.40,1.289,372.0
16216,PickPut,323,10,8039503,2025-12-02 14:33:02.530,2025-12-02,108.380,3.25,0.205,139.0
16217,PickPut,323,10,8039503,2025-12-02 14:33:40.630,2025-12-02,38.100,7.60,1.275,660.0
16284,AssignmentOpen,323,10,8039503,2025-12-02 16:13:45.210,2025-12-02,133.847,NaN,NaN,NaN
16285,PickPut,323,10,8039503,2025-12-02 16:18:52.623,2025-12-02,307.413,10.45,0.947,NaN
16286,PickPut,323,10,8039503,2025-12-02 16:40:53.280,2025-12-02,NaN,10.45,0.947,0.0

In [66]:
user323.sort_values(by="Timestamp").iloc[97:115]

,ActivityCode,UserID,WorkCode,AssignmentID,Timestamp,Date,Time_Delta_sec,Weight,Cube,Travel_Distance
16284,AssignmentOpen,323,10,8039503,2025-12-02 16:13:45.210,2025-12-02,133.847,NaN,NaN,NaN
16285,PickPut,323,10,8039503,2025-12-02 16:18:52.623,2025-12-02,307.413,10.45,0.947,NaN
16286,PickPut,323,10,8039503,2025-12-02 16:40:53.280,2025-12-02,NaN,10.45,0.947,0.0
16287,AssignmentOpen,323,10,8039715,2025-12-02 16:42:38.077,2025-12-02,104.797,NaN,NaN,NaN
16288,PickPut,323,10,8039715,2025-12-02 16:45:21.680,2025-12-02,163.603,35.85,0.903,NaN
16289,PickPut,323,10,8039715,2025-12-02 16:46:58.667,2025-12-02,96.987,4.80,0.859,232.0
16290,PickPut,323,10,8039715,2025-12-02 16:48:36.850,2025-12-02,98.183,1.65,0.238,629.0
16291,PickPut,323,10,8039715,2025-12-02 16:49:13.310,2025-12-02,36.460,20.55,1.925,279.0
16292,PickPut,323,10,8039715,2025-12-02 16:49:34.253,2025-12-02,20.943,4.50,0.409,0.0
16293,PickPut,323,10,8039715,2025-12-02 16:56:35.550,2025-12-02,421.297,1.05,0.253,501.0
16294,PickPut,323,10,8039715,2025-12-02 16:58:14.350,2025-12-02,98.800,16.90,3.260,589.0
16295,PickPut,323,10,8039715,2025-12-02 16:59:57.600,2025-12-02,103.250,3.75,0.516,282.0
16296,PickPut,323,10,8039715,2025-12-02 17:01:17.530,2025-12-02,79.930,5.80,1.415,263.0
16297,PickPut,323,10,8039715,2025-12-02 17:01:46.460,2025-12-02,28.930,20.75,1.969,675.0
16298,PickPut,323,10,8039715,2025-12-02 17:02:32.483,2025-12-02,46.023,4.65,0.409,0.0
16299,PickPut,323,10,8039715,2025-12-02 17:09:40.357,2025-12-02,427.874,12.74,0.920,415.0
16300,PickPut,323,10,8039715,2025-12-02 17:11:32.613,2025-12-02,112.256,0.10,0.010,227.0
16301,PickPut,323,10,8039715,2025-12-02 17:12:42.090,2025-12-02,69.477,5.70,1.200,18.0